# This is a basic workflow to help you get started with Actions

name: Deploy docker images

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Build Identity docker image", "Build PierogiesBot docker image", "Build TheDungeonGuide docker images"]
    types: [completed] #requested
    
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Only on successful docker build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd services
            ./update-images.sh
