name: Review PierogiesBot
on:
  push:
    paths:
      - Sources/PierogiesBot/**
      - Tests/PierogiesBot/**
      - Sources/Shared/**
      - Tests/Shared/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        env:
          DOTNET_ROLL_FORWARD: Major
        shell: powershell
        run: |
          dotnet test --filter "cat=Unit&cat=PierogiesBot"
