name: Review TheDungeonGuide
on:
  push:
    paths:
      - Sources/TheDungeonGuide/**
      - Tests/TheDungeonGuide/**
      - Sources/Shared/**
      - Tests/Shared/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        shell: powershell
        run: |
          dotnet test --filter "cat=Unit&cat=TheDungeonGuide"
